name: manga_app
description: "A Flutter manga reading application."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  firebase_messaging: ^15.2.4
  firebase_app_check: ^0.3.2+5
  flutter_screenutil: ^5.9.3
  carousel_slider: ^5.0.0
  photo_view: ^0.15.0
  shared_preferences: ^2.5.3
  syncfusion_flutter_pdfviewer: ^29.1.33
  provider: ^6.1.2
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  intl: ^0.19.0
  google_fonts: ^5.1.0
  flutter_riverpod: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1 # Added for icon generation

flutter:
  uses-material-design: true
  assets:
    - assets/icons/ # Added to include your icon

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png" # Path to your icon
  # Optional: Add adaptive icon config for Android
  adaptive_icon_background: "#FFFFFF" # Background color for adaptive icon
  adaptive_icon_foreground: "assets/icons/app_icon.png"
