// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQLshtahGOx3uVZHj-FOer-x6oWGDeOYc',
    appId: '1:1007988310802:web:7c8b1593506c837dcf69cb',
    messagingSenderId: '1007988310802',
    projectId: 'mangareader-f1938',
    authDomain: 'mangareader-f1938.firebaseapp.com',
    storageBucket: 'mangareader-f1938.firebasestorage.app',
    measurementId: 'G-DTPD6E0QL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX0rDTiqO7SIiS7-TeXFh37p-o1UbgmJ0',
    appId: '1:1007988310802:android:18cd64e50e912c74cf69cb',
    messagingSenderId: '1007988310802',
    projectId: 'mangareader-f1938',
    storageBucket: 'mangareader-f1938.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwCmRnshzCl-ip3mZk9yyxdHWfq6nRMAg',
    appId: '1:1007988310802:ios:8758686dbb3e04d7cf69cb',
    messagingSenderId: '1007988310802',
    projectId: 'mangareader-f1938',
    storageBucket: 'mangareader-f1938.firebasestorage.app',
    iosBundleId: 'com.example.mangaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwCmRnshzCl-ip3mZk9yyxdHWfq6nRMAg',
    appId: '1:1007988310802:ios:8758686dbb3e04d7cf69cb',
    messagingSenderId: '1007988310802',
    projectId: 'mangareader-f1938',
    storageBucket: 'mangareader-f1938.firebasestorage.app',
    iosBundleId: 'com.example.mangaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQLshtahGOx3uVZHj-FOer-x6oWGDeOYc',
    appId: '1:1007988310802:web:6b5d5499b21dd3a3cf69cb',
    messagingSenderId: '1007988310802',
    projectId: 'mangareader-f1938',
    authDomain: 'mangareader-f1938.firebaseapp.com',
    storageBucket: 'mangareader-f1938.firebasestorage.app',
    measurementId: 'G-RHTBBXW55Z',
  );
}
